apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: example-order-service
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/ryandjf/example-order-service
